// apps/web/src/lib/components/auth-branding.svelte
<script lang="ts">
</script>

<div class="hidden flex-col bg-zinc-900 text-white lg:flex">
	<div class="flex flex-1 flex-col p-10 justify-between relative z-20">
		<div class="flex items-center text-lg font-medium">
			<svg
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
				class="mr-2 h-6 w-6"
			>
				<path d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3" />
			</svg>
			hasu
		</div>
	</div>
</div>

// frontend/src/components/AuthBranding.vue
<script setup lang="ts"></script>

<template>
  <div class="hidden flex-col bg-zinc-900 text-white lg:flex">
    <div class="flex flex-1 flex-col p-10 justify-between relative z-20">
      <div class="flex items-center text-lg font-medium">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="mr-2 h-6 w-6"
        >
          <path d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3" />
        </svg>
        Godploy
      </div>
    </div>
  </div>
</template>
